name: Ruby

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: '3.2.2'
            os: ubuntu-latest
            task: 'bundle exec rake'
          - ruby: '2.6'
            os: ubuntu-22.04
            task: 'bundle exec rspec'
            gemfile: 'gemfiles/ruby26.gemfile'

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile || 'Gemfile' }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: ${{ matrix.task }}
